setup/urls.py
from django.urls import path
from django.conf.urls.static import static
from setup import settings

from filmes.views import FilmeCreateView, FilmeDeleteView, FilmeDetailView, FilmeListView, FilmeUpdateView, PlaylistCreateView, PlaylistDeleteView,PlaylistDetailView, PlaylistListView, PlaylistUpdateView

urlpatterns = [
  path('', PlaylistListView.as_view(), name='playlist_list'),
    path('create/',PlaylistCreateView.as_view(),name='playlist_create'),
    path('<int:pk>/', PlaylistDetailView.as_view(),name='playlist_detail'),
    path('<int:pk>/edit/', PlaylistUpdateView.as_view(), name='playlist_update'),
    path('<int:pk>/delete/', PlaylistDeleteView.as_view(), name='playlist_delete'),

    path('filmes/', FilmeListView.as_view(),name='filme_list'),
    path('filmes/<int:pk>/', FilmeDetailView.as_view(), name='filme_detail'),
    path('filmes/create/', FilmeCreateView.as_view(), name='filme_create'),
    path('filmes/<int:pk>/edit/', FilmeUpdateView.as_view(), name='filme_update'),
    path('filmes/<int:pk>/delete/', FilmeDeleteView.as_view(), name='filme_delete')
] +static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

filmes/models.py
from django.db import models
from django.core.validators import FileExtensionValidator

class Filmes(models.Model):
    titulo = models.CharField(max_length=100)
    produtora = models.CharField(max_length=100)
    atores = models.CharField(max_length=100)
    capa = models.ImageField(upload_to='capas/', validators=[FileExtensionValidator(['png', 'jpg', 'jpeg'])])

    def __str___(self):
        return f"{self.titulo} {self.atores}"
    
class Playlist(models.Model):
    nome = models.CharField(max_length=100)
    filmes = models.ManyToManyField(Filmes)

    def __str__(self):
        return self.nome

filmes/forms.py
from django import forms 
from .models import Playlist, Filmes

class PlaylistForm(forms.ModelForm):
    class Meta:
        model = Playlist
        fields = '__all__'

class FilmeForm(forms.ModelForm):
    class Meta:
        model = Filmes
        fields = '__all__'

filmes/views.py
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from filmes.forms import FilmeForm, PlaylistForm
from filmes.models import Filmes, Playlist 

class PlaylistListView(ListView):
    model = Playlist
    template_name = 'playlist/playlist_list.html'
    paginate_by = 5
    context_object_name = 'playlists'
    queryset = Playlist.objects.order_by('-id')

class PlaylistDetailView(DetailView):
    model = Playlist 
    template_name = 'playlist/playlist_detail.html'
    context_object_name = 'playlists'

class PlaylistCreateView(CreateView):
    model = Playlist
    form_class = PlaylistForm
    template_name = 'playlist/playlist_form.html'
    success_url = reverse_lazy('playlist_list')

class PlaylistUpdateView(UpdateView):
    model = Playlist
    fields = ['nome', 'filmes']
    template_name = 'playlist/playlist_form.html'
    success_url = reverse_lazy('playlist_list')

class PlaylistDeleteView(DeleteView):
    model = Playlist
    success_url = reverse_lazy('playlist_list')   

    #filme crud

class FilmeListView(ListView):
    model = Filmes
    template_name = 'filmes/filme_list.html'

class FilmeCreateView(CreateView):
    model = Filmes
    form_class = FilmeForm
    template_name = 'filmes/filme_form.html'
    success_url = reverse_lazy('filme_list')    

class FilmeDetailView(DetailView):
    model = Filmes
    form_class = FilmeForm
    template_name = 'filmes/filmes_form.html'

class FilmeUpdateView(UpdateView):
    model = Filmes
    form_class = FilmeForm
    template_name = 'filmes/filme_form.html'
    success_url = reverse_lazy ('filme_list')

class FilmeDeleteView(DeleteView):
    model = Filmes
    template_name = 'filmes/filme_confirm_delete.html'
    success_url = reverse_lazy('filme_list') 

filmes/templates/base.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    {% load bootstrap5 %}
    {% load static %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
</head>
<body>
    
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">Meu Projeto de Filmes</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'playlist_list' %}">Playlists</a>
                    </li>
                    <li> <a class="nav-link active" aria-current="page" href="{% url 'filme_list' %}">Filmes</a></li>
                    </ul>
            </div>
        </div>
    </nav>

    <div class="container">
        {% block content %}
        {% endblock %}
    </div>


</body>
</html>

filmes/templates/filmes/filme_confirm_delete.html
{% extends 'base.html' %}

{% block content %}

<h1>Confirmar Exclusão</h1>
<p>Tem certeza que deseja excluir o filme "{{ object.nome }}"?</p>
<form method="POST">
    {% csrf_token %}
    <input type="submit" value="Sim">
    <a href="{% url 'playlist_detail' object.pk %}">Não</a>
</form>

{% endblock %}

filmes/templates/filmes/filme_detail.html
{% extends 'base.html' %}

{% block content %}

<h2>{{ object.titulo }}</h2>
<p>Produtora: {{ object.produtora }}</p>
<p>Atores: {{ object.atores }}</p>
<p>Playlists:
    {% for playlist in object.playlist_set.all %}
        {{ playlist.nome }}
    {% endfor %}
</p>

{% endblock %}

filmes/templates/filmes/filme_form.html
{% extends 'base.html' %}

{% block content %}

<h1>{% if form.instance.pk %}Editar{% else %}Criar{% endif %} Filme</h1>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Salvar</button>
</form>

{% endblock %}

filmes/templates/filmes/filme_list.html
{% extends 'base.html' %}

{% block content %}

<a href="{% url 'filme_create' %}" class="btn btn-primary mb-3">Criar Filme</a>

<ul>
    {% for filme in object_list %}
        <li>{{ filme.titulo }} - {{ filme.produtora }}
            <img src="{{ filme.capa.url }}" alt="{{ filme.titulo }}" width=100>
            <a href="{% url 'filme_detail' filme.pk %}" class="btn btn-primary">Detalhes</a>
            <a href="{% url 'filme_update' filme.pk %}" class="btn btn-secondary">Editar</a>
            <a href="{% url 'filme_delete' filme.pk %}" class="btn btn-danger">Excluir</a>
        </li>
    {% endfor %}
</ul>



{% endblock %}

filmes/templates/playlist/playlist_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
<h1>Confirmar Exclusão</h1>
<p>Tem certeza que deseja excluir a playlist "{{ playlists.nome }}"?</p>
<form method="POST">
    {% csrf_token %}
    <input type="submit" value="Sim">
    <a href="{% url 'playlist_detail' playlists.pk %}">Não</a>
</form>
{% endblock %}

filmes/templates/playlist/playlist_detail.html
{% extends 'base.html' %}

{% block content %}

<h2>{{ playlists.nome }}</h2>
<ul>
    {% for filme in playlists.filmes.all %}
    <li>{{ filme.titulo }} - {{ filme.produtora }} - <img src="{{ filme.capa.url }}" alt="{{ filme.titulo }}" width=100></li>
    {% endfor %}
</ul>
<a href="{% url 'playlist_update' playlists.pk %}">Editar</a>
<a href="{% url 'playlist_delete' playlists.pk %}">Excluir</a>

{% endblock %}

filmes/templates/playlist/playlist_form.html
{% extends 'base.html' %}

{% block content %}

<h1>{% if form.instance.pk %}Editar{% else %}Criar{% endif %} Playlist</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Salvar</button>
</form>

{% endblock %}

filmes/templates/playlist/playlist_list.html
{% extends 'base.html' %}

{% block content %}

<a href="{% url 'playlist_create' %}" class="btn btn-primary mb-3">Criar Playlist</a>


{% for playlist in playlists %}
<li>
    {{ playlist.nome }}
    
    <a href="{% url 'playlist_detail' playlist.pk %}">Detalhes</a>
    <a href="{% url 'playlist_update' playlist.pk %}">Editar</a>
    <a href="{% url 'playlist_delete' playlist.pk %}">Excluir</a>
</li>

{% endfor %}
</ul>

<!-- Paginação -->
<nav aria-label="Navegação de páginas">
    <ul class="pagination">
        {% if page_obj.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page=1" aria-label="Primeira">
                    <span aria-hidden="true">&laquo;&laquo;</span>
                </a>
            </li>
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Anterior">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
        {% else %}
            <li class="page-item disabled"><span class="page-link">&laquo;&laquo;</span></li>
            <li class="page-item disabled"><span class="page-link">&laquo;</span></li>
        {% endif %}

        <li class="page-item active">
            <span class="page-link">Página {{ page_obj.number }} de {{ page_obj.paginator.num_pages }}</span>
        </li>

        {% if page_obj.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Próxima">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}" aria-label="Última">
                    <span aria-hidden="true">&raquo;&raquo;</span>
                </a>
            </li>
        {% else %}
            <li class="page-item disabled"><span class="page-link">&raquo;</span></li>
            <li class="page-item disabled"><span class="page-link">&raquo;&raquo;</span></li>
        {% endif %}
    </ul>
</nav>
</div>
{% endblock %}